### ISSUE TITLE
CQRS Example services respond "No Service was found"

### ISSUE THREAD

**Issue by fsomme2s** [hammock-project/hammock-examples#3]
Hi,
the cqrs example looks interesting. but when I download it and run main() in BookApplication, it's returning an error response in html on /books: "no service was found"

Log says:
Can't find the the request for http://localhost:8080/books/'s Observer

**Comment by johnament** [comment]
I just ran it locally (noticed it wasn't pointing to the final release so fixed that).  Can you paste the console output?

**Comment by fsomme2s** [comment]
`Feb 02, 2017 1:28:16 PM org.jboss.weld.bootstrap.WeldStartup <clinit>
INFO: WELD-000900: 2.4.1 (Final)
Feb 02, 2017 1:28:16 PM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 5.2.4.Final
Feb 02, 2017 1:28:16 PM org.apache.deltaspike.core.impl.config.EnvironmentPropertyConfigSourceProvider <init>
INFORMATION: Custom config found by DeltaSpike. Name: 'META-INF/apache-deltaspike.properties', URL: 'jar:file:/C:/Users/FSommer/.m2/repository/org/apache/deltaspike/modules/deltaspike-jpa-module-impl/1.7.1/deltaspike-jpa-module-impl-1.7.1.jar!/META-INF/apache-deltaspike.properties'
Feb 02, 2017 1:28:16 PM org.apache.deltaspike.core.impl.config.EnvironmentPropertyConfigSourceProvider <init>
INFORMATION: Custom config found by DeltaSpike. Name: 'hammock.properties', URL: 'jar:file:/C:/Users/FSommer/.m2/repository/ws/ament/hammock/web-spi/1.1/web-spi-1.1.jar!/hammock.properties'
Feb 02, 2017 1:28:16 PM org.apache.deltaspike.core.util.ProjectStageProducer initProjectStage
INFORMATION: Computed the following DeltaSpike ProjectStage: Production
Feb 02, 2017 1:28:16 PM org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory create
INFO: WELD-ENV-000020: Using jandex for bean discovery
Feb 02, 2017 1:28:17 PM org.jboss.weld.bootstrap.WeldStartup startContainer
INFO: WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
Feb 02, 2017 1:28:17 PM org.jboss.weld.event.ExtensionObserverMethodImpl checkRequiredTypeAnnotations
INFO: WELD-000411: Observer method [BackedAnnotatedMethod] protected org.apache.deltaspike.core.impl.exclude.extension.ExcludeExtension.vetoBeans(@Observes ProcessAnnotatedType, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
Feb 02, 2017 1:28:17 PM org.jboss.weld.event.ExtensionObserverMethodImpl checkRequiredTypeAnnotations
INFO: WELD-000411: Observer method [BackedAnnotatedMethod] protected org.apache.deltaspike.core.impl.interceptor.GlobalInterceptorExtension.promoteInterceptors(@Observes ProcessAnnotatedType, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
Feb 02, 2017 1:28:17 PM org.jboss.weld.event.ExtensionObserverMethodImpl checkRequiredTypeAnnotations
INFO: WELD-000411: Observer method [BackedAnnotatedMethod] org.apache.deltaspike.data.impl.RepositoryExtension.processAnnotatedType(@Observes ProcessAnnotatedType<X>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
Feb 02, 2017 1:28:17 PM org.jboss.weld.event.ExtensionObserverMethodImpl checkRequiredTypeAnnotations
INFO: WELD-000411: Observer method [BackedAnnotatedMethod] protected org.apache.deltaspike.core.impl.message.MessageBundleExtension.detectInterfaces(@Observes ProcessAnnotatedType) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
Feb 02, 2017 1:28:17 PM org.jboss.weld.event.ExtensionObserverMethodImpl checkRequiredTypeAnnotations
INFO: WELD-000411: Observer method [BackedAnnotatedMethod] public org.apache.deltaspike.partialbean.impl.PartialBeanBindingExtension.findInvocationHandlerBindings(@Observes ProcessAnnotatedType<X>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
Feb 02, 2017 1:28:17 PM org.jboss.weld.logging.ValidatorLogger$7 log
WARN: WELD-001478: Interceptor class org.apache.deltaspike.proxy.util.EnableInterceptorsInterceptor is enabled for the application and for the bean archive /C:/Users/FSommer/.m2/repository/org/apache/deltaspike/modules/deltaspike-proxy-module-api/1.7.1/deltaspike-proxy-module-api-1.7.1.jar. It will only be invoked in the @Priority part of the chain.
Feb 02, 2017 1:28:17 PM org.jboss.weld.logging.ValidatorLogger$7 log
WARN: WELD-001478: Interceptor class org.apache.deltaspike.jpa.impl.transaction.TransactionalInterceptor is enabled for the application and for the bean archive /C:/Users/FSommer/.m2/repository/org/apache/deltaspike/modules/deltaspike-jpa-module-impl/1.7.1/deltaspike-jpa-module-impl-1.7.1.jar. It will only be invoked in the @Priority part of the chain.
Feb 02, 2017 1:28:17 PM org.jboss.weld.logging.ValidatorLogger$7 log
WARN: WELD-001478: Interceptor class org.apache.deltaspike.core.impl.throttling.ThrottledInterceptor is enabled for the application and for the bean archive /C:/Users/FSommer/.m2/repository/org/apache/deltaspike/core/deltaspike-core-impl/1.7.1/deltaspike-core-impl-1.7.1.jar. It will only be invoked in the @Priority part of the chain.
Feb 02, 2017 1:28:17 PM org.jboss.weld.logging.ValidatorLogger$7 log
WARN: WELD-001478: Interceptor class org.apache.deltaspike.core.impl.lock.LockedInterceptor is enabled for the application and for the bean archive /C:/Users/FSommer/.m2/repository/org/apache/deltaspike/core/deltaspike-core-impl/1.7.1/deltaspike-core-impl-1.7.1.jar. It will only be invoked in the @Priority part of the chain.
Feb 02, 2017 1:28:17 PM org.jboss.weld.logging.ValidatorLogger$7 log
WARN: WELD-001478: Interceptor class org.apache.deltaspike.core.impl.future.FutureableInterceptor is enabled for the application and for the bean archive /C:/Users/FSommer/.m2/repository/org/apache/deltaspike/core/deltaspike-core-impl/1.7.1/deltaspike-core-impl-1.7.1.jar. It will only be invoked in the @Priority part of the chain.
Feb 02, 2017 1:28:18 PM org.jboss.weld.bootstrap.Validator validateCustomBean
WARN: WELD-001473: javax.enterprise.inject.spi.Bean implementation org.apache.cxf.cdi.CdiBusBean@78e16155 declared a normal scope but does not implement javax.enterprise.inject.spi.PassivationCapable. It won't be possible to inject this bean into a bean with a passivating scope (@SessionScoped, @ConversationScoped). This can be fixed by assigning the Bean implementation a unique id by implementing the PassivationCapable interface.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Feb 02, 2017 1:28:18 PM org.jboss.weld.environment.servlet.Listener contextInitialized
INFO: WELD-ENV-001007: Initialize Weld using ServletContextListener
Feb 02, 2017 1:28:18 PM org.jboss.weld.environment.servlet.WeldServletLifecycle findContainer
INFO: WELD-ENV-001002: Container detection skipped - custom container class loaded: ws.ament.hammock.bootstrap.weld.HammockContainer.
Feb 02, 2017 1:28:18 PM ws.ament.hammock.web.spi.WebServerConfiguration logPort
INFORMATION: Starting webserver on http://0.0.0.0:8080
Feb 02, 2017 1:28:18 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.3.6.Final
Feb 02, 2017 1:28:18 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.3.6.Final
Feb 02, 2017 1:28:18 PM org.jboss.weld.environment.se.WeldContainer complete
INFO: WELD-ENV-002003: Weld SE container STATIC_INSTANCE initialized
Feb 02, 2017 1:29:59 PM org.apache.cxf.transport.servlet.ServletController invoke
WARNUNG: Can't find the the request for http://localhost:8080/books/'s Observer 
`
Well... this is everything from startup to request

**Comment by johnament** [comment]
Are you running this inside your IDE?

**Comment by fsomme2s** [comment]
Yes... not good?

**Comment by johnament** [comment]
Try now.  I just added a `META-INF/beans.xml` to the example.  It was missing, so if you were running it using capsule, or in an IDE it would have given you this error.

**Comment by johnament** [comment]
Sorry, didn't mean to close.  Let me know how it turns out.

**Comment by fsomme2s** [comment]
argh damnit, why do I always forget about the bean.xml? Now it works...

Thanks for your help!

**Comment by johnament** [comment]
No problem! Let me know if you run into any more issues.
